import { CreditApplication, User } from './types';

const generateId = () => Math.random().toString(36).substr(2, 9);

export const mockUser: User = {
  id: '1',
  name: 'Sarah Anderson',
  email: 'sarah.anderson@intellicredit.com',
  role: 'manager',
  joinedAt: new Date('2023-01-15'),
};

export const mockApplications: CreditApplication[] = [
  {
    id: generateId(),
    company: {
      id: generateId(),
      name: 'TechFlow Solutions Inc.',
      registrationNumber: 'TX-2019-001234',
      registrationType: 'C-Corporation',
      foundedYear: 2019,
      location: 'Austin, TX',
      address: '123 Innovation Drive',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
      country: 'USA',
      phoneNumber: '+1 (512) 555-0123',
      email: 'info@techflow.com',
      website: 'www.techflow.com',
    },
    businessDetails: {
      industry: 'Software Development',
      subIndustry: 'SaaS',
      numberOfEmployees: 45,
      annualRevenue: 2500000,
      businessStage: 'Growth',
      yearlyGrowth: 35,
      mainProducts: ['Cloud Analytics Platform', 'Data Integration Tools'],
      keyCustomers: 'Fortune 500 companies',
    },
    documents: [
      {
        id: generateId(),
        name: 'Financial Statements 2023.pdf',
        type: 'financial',
        size: 2400000,
        uploadedAt: new Date('2024-01-15'),
        url: '#',
      },
      {
        id: generateId(),
        name: 'Tax Returns 2023.pdf',
        type: 'tax',
        size: 1500000,
        uploadedAt: new Date('2024-01-15'),
        url: '#',
      },
      {
        id: generateId(),
        name: 'Business Plan.pdf',
        type: 'business',
        size: 3200000,
        uploadedAt: new Date('2024-01-15'),
        url: '#',
      },
    ],
    bankingInformation: {
      bankName: 'First National Bank',
      accountNumber: '****1234',
      accountType: 'Business Checking',
      yearsWithBank: 4,
    },
    financialMetrics: {
      totalAssets: 5200000,
      totalLiabilities: 1800000,
      equity: 3400000,
      annualRevenue: 2500000,
      netIncome: 450000,
      operatingCashFlow: 380000,
      debtToEquityRatio: 0.53,
      currentRatio: 1.85,
      profitMargin: 0.18,
    },
    creditAssessment: {
      creditScore: 745,
      riskRating: 'low',
      riskFactors: {
        industryRisk: 'low',
        financialRisk: 'low',
        managementRisk: 'low',
        marketRisk: 'medium',
        operationalRisk: 'low',
      },
      recommendation: 'Approved - Excellent credit profile with strong financial position',
      debtCapacity: 1200000,
      approvalProbability: 0.92,
    },
    analysisStatus: [
      {
        step: 'document_verification',
        status: 'completed',
        completedAt: new Date('2024-01-20'),
      },
      {
        step: 'financial_analysis',
        status: 'completed',
        completedAt: new Date('2024-01-22'),
      },
      {
        step: 'risk_assessment',
        status: 'completed',
        completedAt: new Date('2024-01-23'),
      },
      {
        step: 'credit_scoring',
        status: 'completed',
        completedAt: new Date('2024-01-24'),
      },
      {
        step: 'report_generation',
        status: 'completed',
        completedAt: new Date('2024-01-25'),
      },
    ],
    requestedAmount: 500000,
    createdAt: new Date('2024-01-15'),
    submittedAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-25'),
    status: 'approved',
    notes: 'Strong financial performance. Consistent revenue growth.',
  },
  {
    id: generateId(),
    company: {
      id: generateId(),
      name: 'Global Manufacturing Ltd.',
      registrationNumber: 'OH-2010-005678',
      registrationType: 'LLC',
      foundedYear: 2010,
      location: 'Columbus, OH',
      address: '456 Industrial Blvd',
      city: 'Columbus',
      state: 'OH',
      zipCode: '43085',
      country: 'USA',
      phoneNumber: '+1 (614) 555-0456',
      email: 'contact@globalmanuf.com',
      website: 'www.globalmanuf.com',
    },
    businessDetails: {
      industry: 'Manufacturing',
      subIndustry: 'Industrial Equipment',
      numberOfEmployees: 320,
      annualRevenue: 18500000,
      businessStage: 'Mature',
      yearlyGrowth: 8,
      mainProducts: ['Industrial Compressors', 'Hydraulic Systems'],
      keyCustomers: 'Major automotive and aerospace companies',
    },
    documents: [
      {
        id: generateId(),
        name: 'Audited Financials 2023.pdf',
        type: 'financial',
        size: 4100000,
        uploadedAt: new Date('2024-02-01'),
        url: '#',
      },
      {
        id: generateId(),
        name: 'Bank Statements.pdf',
        type: 'banking',
        size: 2800000,
        uploadedAt: new Date('2024-02-01'),
        url: '#',
      },
    ],
    bankingInformation: {
      bankName: 'Chase Business Banking',
      accountNumber: '****5678',
      accountType: 'Business Money Market',
      yearsWithBank: 12,
    },
    financialMetrics: {
      totalAssets: 24500000,
      totalLiabilities: 9200000,
      equity: 15300000,
      annualRevenue: 18500000,
      netIncome: 1480000,
      operatingCashFlow: 2100000,
      debtToEquityRatio: 0.6,
      currentRatio: 1.95,
      profitMargin: 0.08,
    },
    creditAssessment: {
      creditScore: 682,
      riskRating: 'medium',
      riskFactors: {
        industryRisk: 'medium',
        financialRisk: 'medium',
        managementRisk: 'low',
        marketRisk: 'medium',
        operationalRisk: 'medium',
      },
      recommendation: 'Conditional Approval - Stable business with moderate debt levels',
      debtCapacity: 3500000,
      approvalProbability: 0.68,
    },
    analysisStatus: [
      {
        step: 'document_verification',
        status: 'completed',
        completedAt: new Date('2024-02-05'),
      },
      {
        step: 'financial_analysis',
        status: 'completed',
        completedAt: new Date('2024-02-07'),
      },
      {
        step: 'risk_assessment',
        status: 'in_progress',
        estimatedTimeRemaining: 4,
      },
      {
        step: 'credit_scoring',
        status: 'pending',
      },
      {
        step: 'report_generation',
        status: 'pending',
      },
    ],
    requestedAmount: 2000000,
    createdAt: new Date('2024-02-01'),
    submittedAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-08'),
    status: 'under_review',
    notes: 'Manufacturing sector shows cyclical patterns. Monitoring market conditions.',
  },
  {
    id: generateId(),
    company: {
      id: generateId(),
      name: 'Green Energy Ventures',
      registrationNumber: 'CA-2022-009012',
      registrationType: 'C-Corporation',
      foundedYear: 2022,
      location: 'San Francisco, CA',
      address: '789 Solar Lane',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
      phoneNumber: '+1 (415) 555-0789',
      email: 'team@greenenergy.com',
      website: 'www.greenenergy.com',
    },
    businessDetails: {
      industry: 'Renewable Energy',
      subIndustry: 'Solar Installation',
      numberOfEmployees: 28,
      annualRevenue: 850000,
      businessStage: 'Early Growth',
      yearlyGrowth: 180,
      mainProducts: ['Residential Solar Systems', 'Commercial Solar Solutions'],
      keyCustomers: 'Residential homeowners and small businesses',
    },
    documents: [
      {
        id: generateId(),
        name: 'Financial Projections.pdf',
        type: 'financial',
        size: 1900000,
        uploadedAt: new Date('2024-02-10'),
        url: '#',
      },
      {
        id: generateId(),
        name: 'Management Bios.pdf',
        type: 'management',
        size: 1100000,
        uploadedAt: new Date('2024-02-10'),
        url: '#',
      },
    ],
    bankingInformation: {
      bankName: 'Silicon Valley Bank',
      accountNumber: '****9012',
      accountType: 'Business Checking',
      yearsWithBank: 2,
    },
    financialMetrics: {
      totalAssets: 1200000,
      totalLiabilities: 450000,
      equity: 750000,
      annualRevenue: 850000,
      netIncome: 120000,
      operatingCashFlow: 85000,
      debtToEquityRatio: 0.6,
      currentRatio: 1.5,
      profitMargin: 0.14,
    },
    creditAssessment: {
      creditScore: 598,
      riskRating: 'high',
      riskFactors: {
        industryRisk: 'medium',
        financialRisk: 'high',
        managementRisk: 'medium',
        marketRisk: 'medium',
        operationalRisk: 'high',
      },
      recommendation: 'Declined - Insufficient operating history and high operational risk',
      debtCapacity: 200000,
      approvalProbability: 0.15,
    },
    analysisStatus: [
      {
        step: 'document_verification',
        status: 'completed',
        completedAt: new Date('2024-02-12'),
      },
      {
        step: 'financial_analysis',
        status: 'completed',
        completedAt: new Date('2024-02-13'),
      },
      {
        step: 'risk_assessment',
        status: 'completed',
        completedAt: new Date('2024-02-14'),
      },
      {
        step: 'credit_scoring',
        status: 'completed',
        completedAt: new Date('2024-02-14'),
      },
      {
        step: 'report_generation',
        status: 'completed',
        completedAt: new Date('2024-02-15'),
      },
    ],
    requestedAmount: 300000,
    createdAt: new Date('2024-02-10'),
    submittedAt: new Date('2024-02-11'),
    updatedAt: new Date('2024-02-15'),
    status: 'rejected',
    notes: 'Company is too new with limited track record. Operational risks are high.',
  },
  {
    id: generateId(),
    company: {
      id: generateId(),
      name: 'Metropolitan Healthcare Corp',
      registrationNumber: 'NY-2015-003456',
      registrationType: 'C-Corporation',
      foundedYear: 2015,
      location: 'New York, NY',
      address: '321 Medical Plaza',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      phoneNumber: '+1 (212) 555-0321',
      email: 'admin@metrohealthcare.com',
      website: 'www.metrohealthcare.com',
    },
    businessDetails: {
      industry: 'Healthcare',
      subIndustry: 'Medical Services',
      numberOfEmployees: 156,
      annualRevenue: 12800000,
      businessStage: 'Growth',
      yearlyGrowth: 22,
      mainProducts: ['Clinic Services', 'Telemedicine Platform'],
      keyCustomers: 'Individual patients and corporate wellness programs',
    },
    documents: [
      {
        id: generateId(),
        name: 'Licensed Audits 2023.pdf',
        type: 'financial',
        size: 3500000,
        uploadedAt: new Date('2024-02-05'),
        url: '#',
      },
    ],
    bankingInformation: {
      bankName: 'Bank of America',
      accountNumber: '****3456',
      accountType: 'Business Checking',
      yearsWithBank: 9,
    },
    financialMetrics: {
      totalAssets: 8900000,
      totalLiabilities: 2100000,
      equity: 6800000,
      annualRevenue: 12800000,
      netIncome: 1920000,
      operatingCashFlow: 1650000,
      debtToEquityRatio: 0.31,
      currentRatio: 2.15,
      profitMargin: 0.15,
    },
    creditAssessment: {
      creditScore: 718,
      riskRating: 'low',
      riskFactors: {
        industryRisk: 'low',
        financialRisk: 'low',
        managementRisk: 'low',
        marketRisk: 'low',
        operationalRisk: 'low',
      },
      recommendation: 'Approved - Strong healthcare provider with excellent credit metrics',
      debtCapacity: 2500000,
      approvalProbability: 0.88,
    },
    analysisStatus: [
      {
        step: 'document_verification',
        status: 'completed',
        completedAt: new Date('2024-02-06'),
      },
      {
        step: 'financial_analysis',
        status: 'completed',
        completedAt: new Date('2024-02-07'),
      },
      {
        step: 'risk_assessment',
        status: 'completed',
        completedAt: new Date('2024-02-08'),
      },
      {
        step: 'credit_scoring',
        status: 'pending',
      },
      {
        step: 'report_generation',
        status: 'pending',
      },
    ],
    requestedAmount: 1500000,
    createdAt: new Date('2024-02-05'),
    submittedAt: new Date('2024-02-06'),
    updatedAt: new Date('2024-02-08'),
    status: 'under_review',
    notes: 'Healthcare sector stable. Strong recurring revenue model.',
  },
];
